# apps/cloud/frontend/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment-frontend.yaml
  - service-frontend.yaml
  - ingress.yaml
  - configmap-frontend.yaml  # Added for Black Friday promotional configuration
