apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics
  namespace: apparel-store
spec:
  replicas: 3
  selector:
    matchLabels:
      app: analytics
  template:
    metadata:
      labels:
        app: analytics
    spec:
      containers:
      - name: analytics
        image: acrname.azurecr.io/analytics:latest
        ports:
        - containerPort: 8080
