apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics
  namespace: apparel-store
spec:
  replicas: 3
  selector:
    matchLabels:
      app: analytics
  template:
    metadata:
      labels:
        app: analytics
    spec:
      containers:
      - name: analytics
        image: nginx:alpine
        ports:
        - containerPort: 80
        env:
        - name: SERVICE_NAME
          value: "analytics-placeholder"
        - name: MESSAGE
          value: "Analytics service placeholder - coming soon!"