apiVersion: v1
kind: Service
metadata:
  name: pricing-service
  namespace: apparel-store
spec:
  selector:
    app: pricing-service
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
